apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.general.toko }}-{{ .Release.Name }}-{{ .Values.general.env }}-nginx-config
  namespace: {{ .Values.general.toko }}-{{ .Release.Name }}-{{ .Values.general.env }}
  labels:
    app.kubernetes.io/part-of: {{ .Values.general.toko }}-{{ .Release.Name }}-{{ .Values.general.env }}
data:
  default.conf: |
    server {
      listen      8080;
      server_name localhost;

      access_log    /dev/stdout main;
      error_log     /dev/stderr;

      root {{ .Values.nginx.documentRoot | default "/var/www/html" }};
      index index.php index.html;

      location ~\.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass {{ .Values.general.toko }}-{{ .Release.Name }}-{{ .Values.general.env }}-phpfpm-service:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
      }
    }