apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.general.toko }}-{{ .Release.Name }}-{{ .Values.general.env }}-pipeline
  namespace: {{ .Values.general.toko }}-{{ .Release.Name }}-{{ .Values.general.env }}
  labels:
    app.kubernetes.io/part-of: {{ .Values.general.toko }}-{{ .Release.Name }}-{{ .Values.general.env }}
spec:
  params:
  - name: repo-url
    type: string
    default: "{{ .Values.pipeline.sourceUrl }}"
  workspaces:
  - name: shared-data
  - name: git-credentials
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    - name: ssh-directory
      workspace: git-credentials
    params:
    - name: url
      value: {{ .Values.pipeline.sourceUrl }}
    - name: cloneAction
      value: {{ .Values.pipeline.cloneAction | default "pull" }}
    - name: gitBranch
      value: {{ .Values.pipeline.branch | default "main" }}