kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.general.toko }}-{{ .Release.Name }}-{{ .Values.general.env }}-route
  namespace: {{ .Values.general.toko }}-{{ .Release.Name }}-{{ .Values.general.env }}
  labels:
    app.kubernetes.io/part-of: {{ .Values.general.toko }}-{{ .Release.Name }}-{{ .Values.general.env }}  
  annotations:
  {{ if eq .Values.route.tlsEnabled "true" }}
    kuberneres.io/tls-acme: "true"
  {{ end }}  
spec:
  host: {{ .Values.route.url }}
  to:
    kind: Service
    name: {{ .Values.general.toko }}-{{ .Release.Name }}-{{ .Values.general.env }}-nginx-service
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
